# Jekyll Resume Theme

# Site settings
title: Ryan Cushen's Resume
email: cushenr@gmail.com
description: Ryan Cushen's resume.
baseurl: "https://ryancushen.com"
url: "https://ryancushen.com"
name: Ryan Cushen
job: Economics Graduate
location: Sydney, Australia
twitter_username: rcushen
github_username:  rcushen
blog_address: http://www.forestforthetree.com
linkedin_address: www.linkedin.com/in/ryancushen
email_address: cushenr@gmail.com

# Build settings
markdown: kramdown
