# Jekyll Resume Theme

# Site settings
title: Ryan Cushen's Resume
email: cushenr@gmail.com
description: Ryan Cushen's resume.
baseurl: "https://ryancushen.com"
url: "https://ryancushen.com"
name: Ryan Cushen
job: Manager at KPMG
location: Melbourne, Australia
github_address: https://github.com/rcushen
blog_address: https://www.forestforthetree.com
linkedin_address: https://www.linkedin.com/in/ryancushen
email_address: cushenr@gmail.com

# Build settings
markdown: kramdown
