# Jekyll Resume Theme

# Site settings
title: MY Resume
email: cushenr@domain.com
description: Ryan Cushen's resume.
baseurl: "http://ryancushen.com"
url: "http://ryancushen.com"
name: Ryan Cushen
job: writer
location: Melbourne, Australia
languages: HTML, CSS and Javascript
twitter_username: rcushen
github_username:  rcushen
codepen_username:  NONE
email_address: cushenr@gmail.com

# Build settings
markdown: kramdown
